[package]
name = "orbitd"
version = "0.1.0"
edition = "2024"

[dependencies]
orbit-dbus = { path = "../../src/orbit-dbus/" }
orbit-api = { path = "../orbit-api/", features = ["host"] }

notify = "8.2.0"
serde = "1.0.228"
serde_yml = "0.0.12"
xdg = "3.0.0"
libloading = "0.8.9"

zbus = "5.12.0"
futures-lite = "2.6.1"

ui = { workspace = true, features = ["sctk", "vulkan", "tracy_full"] }

smithay-client-toolkit = "0.20.0"
wayland-client = "0.31.11"
calloop = "0.14.3"

tracing = "0.1.44"
tracing-subscriber = { version = "0.3.22", features = ["env-filter", "fmt"] }
tracing-log = "0.2.0"
