[workspace]
resolver = "3"
members = [
  "src/orbit-api",
  "src/orbit",
  "src/orbitd",
  "src/orbit-dbus",
  "xtask",
  "modules/wallpaper",
  "modules/bar",
]

[workspace.dependencies]
ui = { git = "https://github.com/Magyx/ui_lib.git", rev = "067ba3452260073c2beaa7b0bb703d6792080c56" }

[profile.release]
codegen-units = 1
lto = true
strip = "symbols"
